#pragma once

#define DEBOUNCE 5

#define ENCODER_RESOLUTION 4

#define RGBLIGHT_LED_COUNT 68
#define RGBLIGHT_LIMIT_VAL 180
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_SLEEP

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27
